Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/bin/nmtpy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vol/bitbucket/al4616/simmt/bin/nmtpy", line 88, in <module>
    setup_experiment(opts, args.suffix)
  File "/vol/bitbucket/al4616/simmt/nmtpytorch/utils/misc.py", line 196, in setup_experiment
    folder.mkdir(parents=True, exist_ok=True)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1277, in mkdir
    if not exist_ok or not self.is_dir():
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1368, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait1'
Fri May 29 18:41:07 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   32C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/bin/nmtpy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vol/bitbucket/al4616/simmt/bin/nmtpy", line 88, in <module>
    setup_experiment(opts, args.suffix)
  File "/vol/bitbucket/al4616/simmt/nmtpytorch/utils/misc.py", line 196, in setup_experiment
    folder.mkdir(parents=True, exist_ok=True)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1277, in mkdir
    if not exist_ok or not self.is_dir():
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1368, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait2'
Fri May 29 18:41:08 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   32C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/bin/nmtpy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vol/bitbucket/al4616/simmt/bin/nmtpy", line 88, in <module>
    setup_experiment(opts, args.suffix)
  File "/vol/bitbucket/al4616/simmt/nmtpytorch/utils/misc.py", line 196, in setup_experiment
    folder.mkdir(parents=True, exist_ok=True)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1277, in mkdir
    if not exist_ok or not self.is_dir():
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1368, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait3'
Fri May 29 18:41:09 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   32C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/bin/nmtpy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vol/bitbucket/al4616/simmt/bin/nmtpy", line 88, in <module>
    setup_experiment(opts, args.suffix)
  File "/vol/bitbucket/al4616/simmt/nmtpytorch/utils/misc.py", line 196, in setup_experiment
    folder.mkdir(parents=True, exist_ok=True)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1277, in mkdir
    if not exist_ok or not self.is_dir():
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1368, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait5'
Fri May 29 18:41:10 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   32C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/bin/nmtpy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vol/bitbucket/al4616/simmt/bin/nmtpy", line 88, in <module>
    setup_experiment(opts, args.suffix)
  File "/vol/bitbucket/al4616/simmt/nmtpytorch/utils/misc.py", line 196, in setup_experiment
    folder.mkdir(parents=True, exist_ok=True)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1277, in mkdir
    if not exist_ok or not self.is_dir():
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1368, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/vol/bitbucket/al4616/miniconda3/envs/simnmt/lib/python3.7/pathlib.py", line 1178, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/homes/al4616/experiments/simnmt/nmtpy/bpe_models/fr-fr/fr-fr-unimodal-w2bpe-wait7'
Fri May 29 18:41:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:06.0 Off |                    0 |
| N/A   32C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
 18:41:12 up  2:51,  1 user,  load average: 0.45, 0.30, 0.33
